services:
  master1:
    image: mysql:8.0
    container_name: master1
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db1_root_password
    secrets:
      - db1_root_password
    ports:
      - "3309:3306"
    volumes:
      - ./db1/my.cnf:/etc/my.cnf
    networks:
      - replication_net

  master2:
    image: mysql:8.0
    container_name: master2
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db2_root_password
    secrets:
      - db2_root_password
    ports:
      - "3307:3306"
    volumes:
      - ./db2/my.cnf:/etc/my.cnf
    networks:
      - replication_net

  master3:
    image: mysql:8.0
    container_name: master3
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db3_root_password
    secrets:
      - db3_root_password
    ports:
      - "3308:3306"
    volumes:
      - ./db3/my.cnf:/etc/my.cnf
    networks:
      - replication_net

secrets:
  db1_root_password:
    file: ./env/db1.env
  db2_root_password:
    file: ./env/db2.env
  db3_root_password:
    file: ./env/db3.env

networks:
  replication_net:
    name: replication_net
    driver: bridge
