services:
  mysql-master:
    image: 'mysql:8.0'
    container_name: mysql-master
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./master/master.sql:/docker-entrypoint-initdb.d/start.sql
      - ./master/master.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}

  mysql-slave1:
    image: 'mysql:8.0'
    container_name: mysql-slave1
    env_file: .env
    ports:
      - "3307:3306"
    volumes:
      - ./slave1/slave1.sql:/docker-entrypoint-initdb.d/start.sql 
      - ./slave1/slave1.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql-master

  mysql-slave2:
    image: 'mysql:8.0'
    container_name: mysql-slave2
    env_file: .env
    ports:
      - "3308:3306"
    volumes:
      - ./slave2/slave2.sql:/docker-entrypoint-initdb.d/start.sql
      - ./slave2/slave2.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql-master
